name: flutter_master
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  url_launcher: ^6.2.1
  google_fonts: ^6.1.0
  analyzer: ^6.2.0
  intl: ^0.18.0
  nylo_framework: ^5.8.0
  pretty_dio_logger: ^1.3.1

  flutter_spinkit: ^5.2.0
#  flutter_swiper_view: ^1.1.8
  card_swiper: ^3.0.1
  cached_network_image: ^3.3.0
  slide_countdown: ^1.3.1

  app:
    path: modules/app

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  #  lints: ^2.0.0
  flutter_test:
    sdk: flutter

# APP ICON - public/assets/app_icon/icon.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "public/assets/app_icon/icon.png"
  remove_alpha_ios: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/assets/fonts/
    - public/assets/images/
    - public/assets/app_icon/
    - lang/
    - .env